baseURL = 'https://kipyegonamos.github.io/'
languageCode = 'en-us'
title = 'kipyegonamos.github.io'
theme = 'sunflower'

[params]
  description = 'Amos Kipyegon personal website'

[caches]
  [caches.images]
    dir = ':cacheDir/images'
